name: PublicPlaytime
version: '${project.version}'
main: me.lifelessnerd.publicplaytime.PublicPlaytime
api-version: 1.19
authors: [ LifelessNerd ]
description: Keeps player playtime neat and public, can be requested in a number of ways in-game
website: https://github.com/LifelessNerd
commands:
  playtime:
    description: Gets the playtime of the provided player.
    usage: /<command> <player>
    aliases:
      - getplaytime
