name: PublicPlaytime
version: '${project.version}'
main: me.lifelessnerd.publicplaytime.PublicPlaytime
api-version: 1.19
authors: [ LifelessNerd ]
description: Keeps player playtime neat and public, can be shown in a number of ways in-game
website: https://github.com/LifelessNerd
commands:
  playtime:
    description: Get playtime of a player in a number of ways.
    usage: /playtime <get/ranking/scoreboard/help>
    aliases:
      - publicplaytime

#  getplaytime:
#    description: Gets the playtime of the provided player.
#    usage: /<command> <player> <days/hours/minutes/seconds/ticks/standard>
#    aliases:
#      - pltm
#      - plt
#  playtimescoreboard:
#    description: Shows the sidebar scoreboard for playtime rankings.
#    usage: /<command> <show/hide> <days/hours/minutes/seconds/ticks> <maxEntries>
#    aliases:
#      - pltsb
#      - pltmsb
#  playtimeranking:
#    description: Shows the rankings for playtime in chat.
#    usage: /<command> <days/hours/minutes/seconds/ticks/standard> <maxEntries>
#    aliases:
#      - pltr
#      - pltmr

